#!/usr/bin/env bash
# Usage: whim cmd [args]
# Summary: run a raw ec2 command
# Help: This will print out when you run `sub help who`.
# You can have multiple lines even!
#
#    Show off an example indented
#
# And maybe start off another one?

set -e

source $_WHIM_ROOT/lib/base.sh

$EC2_HOME/bin/$1
