#!/usr/bin/env bash
# Usage: whim cmd [args]
# Summary: run a raw ec2 command
# Provide whim completions

set -e

source $_WHIM_ROOT/lib/base.sh

if [ "$1" = "--complete" ]; then
  ls -1 $EC2_HOME/bin/ | grep -v '.cmd'
  exit
fi

$EC2_HOME/bin/$@
